name: Generate snake and trophy

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Ariashakoo
          outputs: dist/snake.svg

      - name: Generate trophy.svg
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: 'username=Ariashakoo&theme=radical&margin-w=4&no-bg=true&no-frame=false'
          path: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
